modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="All rights reserved"

[[mods]] #mandatory
modId="sticksdeco" #mandatory
version="0.1.3" #mandatory
displayName="Stick's Decorative" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="sticksdeco.png" #optional
# A text field displayed in the mod UI
#credits="" #optional
# A text field displayed in the mod UI
authors="ULSTICK" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
    Stick's Deco adds a large variety of Decorative Blocks & Furnitures with its own Themes to choose from

    Inspired by Terrarias Furnitures
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.1)"
    ordering="NONE"
    side="BOTH"
